name: Release

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write    

jobs:
  create-minimal-linux-x84_64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Create minimal SDK directory
      run: bash -x create-linux.sh
    - name: Upload tarball
      uses: actions/upload-artifact@v4
      with:
        name: linux-sdk
        path: vulkansdk-linux-minimal*

  create-minimal-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Setup homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Install 7-zip
      run: brew install 7-zip
    - name: Create minimal SDK directory
      run: bash -x create-mac.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-sdk
        path: vulkansdk-macos-minimal*

  github-release:
    needs: [create-minimal-linux-x84_64, create-minimal-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: linux-sdk
      - uses: actions/download-artifact@v3
        with:
          name: macos-sdk
      - run: ls -lha
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            vulkansdk-linux-minimal-x86_64.tar.xz
            vulkansdk-macos-minimal.tar.xz
